spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: LogAccount
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hiberanate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3307/BankPayment?createDatabaseIfNotExist=true
    username: root
    password: admin
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: localhost:29092
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
      function:
        definition : paymentProcessor;paymentCustomerProcessor;inventoryProcessor
      bindings:
        inventoryProcessor-in-0:
          destination: inventory-event
        inventoryProcessor-out-0:
          destination: payment-event
        paymentProcessor-in-0:
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-producer-event
        paymentCustomerProcessor-in-0:
           destination: customer-event
        paymentCustomerProcessor-out-0:
           destination: payment-event
server:
  port: 7082